<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "	<title>Login V1</title>\n";
echo "	<meta charset=\"UTF-8\">\n";
echo "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "<!--===============================================================================================-->	\n";
echo "	<link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.ico\"/>\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\n";
echo "<!--===============================================================================================-->	\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "</head>\n";
echo "<body>\n";
echo "	\n";
echo "	<div class=\"limiter\">\n";
echo "		<div class=\"container-login100\">\n";
echo "			<div class=\"wrap-login100\">\n";
echo "				<div class=\"login100-pic js-tilt\" data-tilt>\n";
echo "					<img src=\"images/img-01.png\" alt=\"IMG\">\n";
echo "				</div>\n";
echo "\n";
echo "				<form class=\"login100-form validate-form\">\n";
echo "					<span class=\"login100-form-title\">\n";
echo "						Member Login\n";
echo "					</span>\n";
echo "\n";
echo "					<div class=\"wrap-input100 validate-input\" data-validate = \"Valid email is required: ex@abc.xyz\">\n";
echo "						<input class=\"input100\" type=\"text\" name=\"email\" placeholder=\"Email\">\n";
echo "						<span class=\"focus-input100\"></span>\n";
echo "						<span class=\"symbol-input100\">\n";
echo "							<i class=\"fa fa-envelope\" aria-hidden=\"true\"></i>\n";
echo "						</span>\n";
echo "					</div>\n";
echo "\n";
echo "					<div class=\"wrap-input100 validate-input\" data-validate = \"Password is required\">\n";
echo "						<input class=\"input100\" type=\"password\" name=\"pass\" placeholder=\"Password\">\n";
echo "						<span class=\"focus-input100\"></span>\n";
echo "						<span class=\"symbol-input100\">\n";
echo "							<i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\n";
echo "						</span>\n";
echo "					</div>\n";
echo "					\n";
echo "					<div class=\"container-login100-form-btn\">\n";
echo "						<button class=\"login100-form-btn\">\n";
echo "							Login\n";
echo "						</button>\n";
echo "					</div>\n";
echo "\n";
echo "					<div class=\"text-center p-t-12\">\n";
echo "						<span class=\"txt1\">\n";
echo "							Forgot\n";
echo "						</span>\n";
echo "						<a class=\"txt2\" href=\"#\">\n";
echo "							Username / Password?\n";
echo "						</a>\n";
echo "					</div>\n";
echo "\n";
echo "					<div class=\"text-center p-t-136\">\n";
echo "						<a class=\"txt2\" href=\"#\">\n";
echo "							Create your Account\n";
echo "							<i class=\"fa fa-long-arrow-right m-l-5\" aria-hidden=\"true\"></i>\n";
echo "						</a>\n";
echo "					</div>\n";
echo "				</form>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "	\n";
echo "\n";
echo "	\n";
echo "<!--===============================================================================================-->	\n";
echo "	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/bootstrap/js/popper.js\"></script>\n";
echo "	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/select2/select2.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/tilt/tilt.jquery.min.js\"></script>\n";
echo "	<script >\n";
echo "		$('.js-tilt').tilt({\n";
echo "			scale: 1.1\n";
echo "		})\n";
echo "	</script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"js/main.js\"></script>\n";
echo "\n";
echo "</body>\n";
echo "</html>";

?>
