<?php

echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "	<title>Login</title>\n";
echo "	<meta charset=\"UTF-8\">\n";
echo "	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n";
echo "<!--===============================================================================================-->	\n";
echo "	<link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.ico\"/>\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\n";
echo "<!--===============================================================================================-->	\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\n";
echo "	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n";
echo "<!--===============================================================================================-->\n";
echo "</head>\n";
echo "<body>\n";
echo "	<style>\n";
echo "        #staff{\n";
echo "            width: 45%;\n";
echo "            margin-left: -400px;\n";
echo "            margin-top: -100px;\n";
echo "        }\n";
echo "        \n";
echo "        #student{\n";
echo "            width: 100%;\n";
echo "            margin-left: 400px;\n";
echo "            margin-top: -120px;\n";
echo "        }\n";
echo "\n";
echo "        #form{\n";
echo "            margin-top: 10px;\n";
echo "        }\n";
echo "\n";
echo "    </style>\n";
echo "    \n";
echo "    \n";
echo "	<div class=\"limiter\">\n";
echo "        \n";
echo "		<div class=\"container-login100\">\n";
echo "            <div class=\"wrap-login100\" id = \"form\"> \n";
echo "            <div class=\"container-login100-form-btn\">\n";
echo "                <button onclick = \"location.href = 'index.php';\" class=\"login100-form-btn\" id = \"staff\">\n";
echo "                    Staff Login\n";
echo "                </button>\n";
echo "            </div>\n";
echo "\n";
echo "            <div class=\"container-login100-form-btn\">\n";
echo "                <button onclick = \"location.href = 'login.html';\" class=\"login100-form-btn\" id = \"student\">\n";
echo "                    Student Login\n";
echo "                </button>\n";
echo "            </div>\n";
echo "			</div>\n";
echo "		</div>\n";
echo "	</div>\n";
echo "	\n";
echo "	\n";
echo "\n";
echo "	\n";
echo "<!--===============================================================================================-->	\n";
echo "	<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/bootstrap/js/popper.js\"></script>\n";
echo "	<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/select2/select2.min.js\"></script>\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"vendor/tilt/tilt.jquery.min.js\"></script>\n";
echo "\n";
echo "<!--===============================================================================================-->\n";
echo "	<script src=\"js/main.js\"></script>\n";
echo "\n";
echo "</body>\n";
echo "</html>";

?>
